version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: zabbix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpwd
      POSTGRES_DB: zabbix
      TZ: Europe/Paris
    volumes:
      - pg_data:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-7.0-latest
    container_name: zabbix-server
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpwd
      POSTGRES_DB: zabbix
      ZBX_DEBUGLEVEL: 3
      TZ: Europe/Paris
    ports:
      - "10051:10051"
    volumes:
      - zbx_alertscripts:/usr/lib/zabbix/alertscripts
      - zbx_external:/usr/lib/zabbix/externalscripts

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-7.0-latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - postgres
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpwd
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Paris
    ports:
      - "8080:8080"  # acc√®s via http://localhost:8080

  zabbix-agent2:
    image: zabbix/zabbix-agent2:ubuntu-7.0-latest
    container_name: zabbix-agent2
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-agent-local
      TZ: Europe/Paris
    depends_on:
      - zabbix-server

volumes:
  pg_data:
  zbx_alertscripts:
  zbx_external:
